### ISSUE TITLE
Toggle Sneak setting not saved

### ISSUE THREAD

**Issue by sm3g** [chylex/Better-Controls#19]
The Toggle Sneak setting is not saved between sessions, at least in my use case.

To reproduce:

1. Launch Minecraft, open game (I'm playing on a server)
2. Open Better Controls Settings
3. Set Toggle Sneak to 'Left Win' key
4. Confirm key binding works as expected
5. Quit Minecraft
6. Launch and open game again
7. Confirm pressing Left Win key no longer toggles sneak
8. Open Better Controls Settings
9. Confirm keybinding for Toggle Sneak shows (No Binding)

Using Minecraft 1.18.2, Vanilla Tweaks modpack, Better Controls v1.2.3

**Comment by chylex** [comment]
Works for me with 1.18.2, using Fabric Loader 0.14.4 and Better Controls without any other mods.

**Comment by chylex** [comment]
I don't know what the problem might be. If it happens with just Better Controls and no other mods, or if you can find exactly which mod conflicts, please reopen the issue.
