### ISSUE TITLE
Update on Modrinth

### ISSUE THREAD

**Issue by srnyx** [chylex/Better-Controls#22]
Upload the updates onto Modrinth. Currently, it only has the 1.15 version.

**Comment by chylex** [comment]
When I have time, I'll look into some automated way to copy the files and information from CF. If it works I'll try to upload all mods, but I'm not going to spend a lot of time on it if it doesn't.

**Comment by srnyx** [comment]
> When I have time, I'll look into some automated way to copy the files and information from CF. If it works I'll try to upload all mods, but I'm not going to spend a lot of time on it if it doesn't.

No rush, someone was able to update the other mod I prefer using (Sneak Hold) and they uploaded it to Modrinth,

**Comment by chylex** [comment]
All versions of Better Controls and my other mods are available on Modrinth now.
