### ISSUE TITLE
Forge failed to load correctly 

### ISSUE THREAD

**Issue by HayMacc** [chylex/Better-Controls#23]
I've been reading the thread and seems that others are having issues with the 1.19 version. I downloaded the correct version (forge) and launched with forge but no success. Been using since 1.16 with no issues until the latest release. Thanks hope it can get worked out.

**Comment by chylex** [comment]
Idk what thread you've been reading, the only version people on CF are talking about is Fabric. Forge made breaking changes in version `41.0.94`, I'll update the mod for newer versions. In the meantime if you're using exactly 1.19 then you can try downgrading to `41.0.93`.

**Comment by chylex** [comment]
Update released.
