### ISSUE TITLE
Better Controls Release 1.2.3b (Fabric) crashes in 1.19.3.

### ISSUE THREAD

**Issue by Cookie-Kurokami** [chylex/Better-Controls#26]
Attempting to open the Controls screen from the pause menu with this mod installed causes the game to crash to desktop, exiting with code -1 (0xffffffffffffffff). Here's the full crash log: https://pastebin.com/pwGNkLd8

**Comment by Cookie-Kurokami** [comment]
Update: I can now confirm that even when the mod is installed by itself, the crashing persists. Here is another crash log: https://pastebin.com/UvVFCdMk

**Comment by chylex** [comment]
Version 1.2.3b was for a 1.19.3 snapshot, looks like the full update broke it. I'll look into it tomorrow.

**Comment by chylex** [comment]
The crash is fixed, I need to fix up some UI before I can release an update.
