### ISSUE TITLE
Crashing in 1.20.1.

### ISSUE THREAD

**Issue by Cookie-Kurokami** [chylex/Better-Controls#27]
The latest version of Better Controls crashes on every attempt to open the configuration menu, as shown in this video here: https://streamable.com/vxdlyh
This occurs even with all other mods disabled. I will share the crash logs below.

Here is one with the other mods installed:
https://pastebin.com/LZYR41Ci

And here is another with Better Controls by itself:
https://pastebin.com/UF9ZBsW6

**Comment by MetricMimic** [comment]
Real
