### ISSUE TITLE
[Feature Request] Custom keybind combinations and more

### ISSUE THREAD

**Issue by markaabo** [chylex/Better-Controls#28]
Hello, i am asking if it would be possible to add a feature that unlocks any key combination for keybinds

So you could have a keybind thats "j + c" and not just modifier things, in addition unlimited combinations would also be amazing like the mod "ReBind" did back in the day but sadly the mod creator seems to have disapeared for years now and its only updated to 1.12 that mod added alot of nice things so if you would be interrested it could maybe be some features added to better controls to make it the ultimate mod for all control related stuff

**Comment by chylex** [comment]
It would probably be possible but I'm not interested in working on this.
