### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by Slooshie1** [chylex/Better-Controls#33]
The mod seems to work fine for a few minutes on Minecraft 1.21, but then crashes a few minutes in. It also crashes when I open the config from Mod Menu. The former issue is seemingly not present without Better Controls. Here is the crash report that generated after being in a world for a few minutes: https://mclo.gs/IKidDzT

**Comment by SJ-Tom** [comment]
bump

**Comment by chylex** [comment]
I'm on vacation.

**Comment by Clozent** [comment]
Have a nice vacation!
