### ISSUE TITLE
Keybind Resetting

### ISSUE THREAD

**Issue by OKaysional** [chylex/Better-Controls#34]
I'm running this on fabric in 1.21 everything's up to date [and im so sorry im so new to mods so i don't know what information u need i know this must be exhausting] but every time I closed minecraft the keybind for toggle sneak resets? I had bound alt to toggle sneak and it worked fine while I'm playing but then I had to rebind every time i opened the game, When I switched to a non-modifier key it stayed bound just fine so I'm not sure this is an issue or intended but I would have prefered to bind to alt so I'm wondering if it's something I can do to let me do that? If not, no biggie thanks for a great mod

**Comment by chylex** [comment]
Like this? It's not getting reset for me, try removing other mods.

![image](https://github.com/chylex/Better-Controls/assets/3685160/481517c4-9c06-4018-996b-e02fda374bc8)

**Comment by chylex** [comment]
Closing as unreproducible.
