### ISSUE TITLE
Survival mode compatibility

### ISSUE THREAD

**Issue by xmbCheasd** [chylex/Better-Controls#36]
Some mod I added can provide flight in survival mode, can you set this mod to work in survival mode?

**Comment by chylex** [comment]
Guessing duplicate of #35.

**Comment by xmbCheasd** [comment]
Ok, wish you can add this compatibility. Thank you.

**Comment by chylex** [comment]
The only possibility of survival flight is with other mods or server plugins, which is something the mod will never interfere with to avoid giving players an unfair advantage.
