### ISSUE TITLE
Always sprint on W

### ISSUE THREAD

**Issue by assasin541** [chylex/Better-Controls#7]
Can you add option to add sprinting always when pressing w?

**Comment by assasin541** [comment]
Mod doesn't work on fabric.

**Comment by chylex** [comment]
I don't consider this a necessary addition when the option to toggle sprinting exists, so I'm not planning to add it. Alternatively, you could use AutoHotkey to reverse the function of your sprint key if that's how you want it to behave.

**Comment by assasin541** [comment]
@chylex how can I do that on fabric? I want to sprint everytime I press W.

**Comment by chylex** [comment]
If you just want to sprint all the time, set the toggle sprint keybind and press it once.

**Comment by assasin541** [comment]
@chylex it disables everytime you hit.

**Comment by chylex** [comment]
I don't know what you mean.

**Comment by assasin541** [comment]
@chylex what do you mean?

**Comment by chylex** [comment]
The toggle sprint keybind works as expected.

**Comment by assasin541** [comment]
@chylex I want to sprint everytime I hold w.

**Comment by chylex** [comment]
As I said, try using the toggle sprint keybind, or if that doesn't work the way you want, try AutoHotkey to reverse the function of your sprint key.

**Comment by assasin541** [comment]
@chylex what autohotkey?

**Comment by chylex** [comment]
It's a program for changing how your keyboard works. It's a bit advanced but can do pretty much anything you want.

**Comment by assasin541** [comment]
@chylex why not mod?

**Comment by chylex** [comment]
As I said, you can use the toggle keybind. If that doesn't work for you, there are other options. I'm not going to be adding the feature to the mod at the moment because the toggle exists so I don't think adding sprint reversal would be worth the effort.
